import assert from 'node:assert/strict'
import fs from 'node:fs'
import { createApplication } from './helpers/application.mjs'
import '../app/core.js'
const { searchRegulations } = globalThis.QuizCore
const data = JSON.parse(fs.readFileSync(new URL('../app/assets/data/regulations.json', import.meta.url)))
assert.deepEqual(searchRegulations('   ', data), [])
assert.deepEqual(searchRegulations('不存在的安规关键词xyz', data), [])
const matches = searchRegulations('工作票', data)
assert.ok(matches.length > 30)
assert.deepEqual(matches, data.clauses.filter(item => item.text.includes('工作票')))
assert.ok(searchRegulations('工作票 签发人', data).every(item => item.text.includes('工作票') && item.text.includes('签发人')))
assert.ok(searchRegulations('12.3.1', data, 'general').some(item => item.ref === '12.3.1'))
assert.ok(searchRegulations('B.1', data, 'coal').some(item => item.kind === 'table'))
assert.deepEqual(searchRegulations('工作票', data, 'coal'), matches.filter(item => item.source === 'coal'))
assert.deepEqual(searchRegulations('gb', data), searchRegulations('GB', data))
assert.doesNotThrow(() => searchRegulations('[.*+?', data))
const { app, run, plain } = createApplication()
run("navigate('regulations')")
assert.equal(run('currentBankId'), null, 'Reference search requires no bank selection')
const input = app.querySelector('#regulation-search')
const change = value => { input.value = value; input.handlers.get('input')({ isComposing: false }) }
change('工作票')
assert.match(app.querySelector('#regulation-search-status').textContent, /已显示 30 条/)
const results = app.querySelector('#regulation-search-results')
results.querySelector('#more-regulations').handlers.get('click')()
assert.match(app.querySelector('#regulation-search-status').textContent, /已显示 60 条/)
input.handlers.get('compositionstart')()
change('工作票 签发人')
assert.equal(run('regulationSearchState.query'), '工作票')
input.handlers.get('compositionend')()
assert.equal(run('regulationSearchState.query'), '工作票 签发人')
assert.equal(run('regulationSearchState.limit'), 30)
app.querySelector('#regulation-source-filter').handlers.get('change')({ target: { value: 'coal' } })
const saved = plain('regulationSearchState')
run("navigate('home'); selectBank('youththeory2'); navigate('regulations')")
assert.deepEqual(plain('regulationSearchState'), saved, 'Bank and navigation changes preserve independent search')
app.querySelector('#clear-regulation-search').handlers.get('click')()
assert.equal(run('regulationSearchState.query'), '')
assert.match(results.innerHTML, /输入关键词/)
change('不存在的安规关键词xyz')
assert.match(results.innerHTML, /未找到相关原文/)
run("regulationSearchState.query = '<script> [.*';")
assert.equal(run("highlightRegulationQuery('<script> [.*')"), '<mark>&lt;script&gt;</mark> <mark>[.*</mark>')
console.log('Regulation search passed: full corpus, source scope, table/reference search, literal escaping, IME, paging, clearing and independent navigation.')
