#!/usr/bin/env python3
"""Embed quiz banks and regulation references for offline/file:// use."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--app", type=Path, default=Path("app"))
    args = parser.parse_args()
    app = args.app.resolve()
    banks = []
    for name in (
        "exam0828.json",
        "safety-week2.json",
        "youth-theory-2.json",
        "safety2024general.json",
        "safety2024coal.json",
    ):
        with (app / "assets" / "data" / name).open(encoding="utf-8") as handle:
            banks.append(json.load(handle))
    payload = json.dumps(banks, ensure_ascii=False, separators=(",", ":"))
    (app / "banks-data.js").write_text(
        "// Generated by scripts/embed_banks.py; do not edit by hand.\n"
        f"window.QUIZ_BANKS={payload};\n",
        encoding="utf-8",
    )
    with (app / "assets" / "data" / "regulations.json").open(encoding="utf-8") as handle:
        regulations = json.load(handle)
    regulation_payload = json.dumps(regulations, ensure_ascii=False, separators=(",", ":"))
    (app / "regulations-data.js").write_text(
        "// Generated by scripts/embed_banks.py; do not edit by hand.\n"
        f"window.SAFETY_REGULATIONS={regulation_payload};\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
