#!/usr/bin/env python3
"""Embed the JSON banks in a script so file:// WebViews need no fetch()."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--app", type=Path, default=Path("app"))
    args = parser.parse_args()
    app = args.app.resolve()
    banks = []
    for name in ("exam0828.json",):
        with (app / "assets" / "data" / name).open(encoding="utf-8") as handle:
            banks.append(json.load(handle))
    payload = json.dumps(banks, ensure_ascii=False, separators=(",", ":"))
    (app / "banks-data.js").write_text(
        "// Generated by scripts/embed_banks.py; do not edit by hand.\n"
        f"window.QUIZ_BANKS={payload};\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
